youcan-shop/cli

- lib/cli/commands/index.ts
- lib/cli/commands/theme/init.ts
- lib/cli/commands/theme/pack.ts
- lib/utils/common.ts
- lib/utils/system/ls.ts
- lib/utils/system/zipFolder.ts
[DOT-X](https://nextmediama.atlassian.net/browse/DOT-X)
> feat: add package command

- lib/cli/commands/theme/dev.ts
- lib/core/themes/preview.ts
- lib/utils/system/zipFolder.ts
[DOT-X](https://nextmediama.atlassian.net/browse/DOT-X)
> feat: add disable hardware acceleration flag

- lib/cli/commands/theme/pack.ts
- lib/utils/system/zipFolder.ts
[DOT-X](https://nextmediama.atlassian.net/browse/DOT-X)
> fix: pack only the theme required folders

- lib/cli/commands/auth/login.ts
- lib/config/messages.ts
- lib/core/client/client.ts
- lib/core/client/types.ts
[DOT-7476](https://nextmediama.atlassian.net/browse/DOT-7476)
[DOT-7476]: https://youcanshop.atlassian.net/browse/DOT-7476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cli > Switch the login to use email/password

- lib/cli/commands/index.ts
- lib/cli/commands/store/switch.ts
- lib/cli/commands/store/types.ts
- lib/config/messages.ts
- lib/core/client/client.ts
[DOT-7477](https://youcanshop.atlassian.net/browse/DOT-7477)
[DOT-7477]: https://youcanshop.atlassian.net/browse/DOT-7477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cli > Add command to switch between development stores

- lib/cli/commands/index.ts
- lib/cli/commands/theme/delete.ts
- lib/cli/commands/theme/dev.ts
- lib/cli/commands/theme/init.ts
- lib/cli/commands/theme/pack.ts
- lib/cli/commands/theme/pull.ts
> Dark - Prefix Commands

- lib/cli/commands/index.ts
- lib/cli/commands/store/info.ts
- lib/cli/commands/theme/delete.ts
- lib/cli/commands/theme/list.ts
- lib/config/messages.ts
- lib/utils/system/stdout.ts
[DOT-7482](https://youcanshop.atlassian.net/browse/DOT-7482)
[DOT-7483](https://youcanshop.atlassian.net/browse/DOT-7483)
[DOT-7482]: https://youcanshop.atlassian.net/browse/DOT-7482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOT-7483]: https://youcanshop.atlassian.net/browse/DOT-7483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cli > Add store info command /  list development stores command

- lib/cli/commands/apps/create.ts
- lib/cli/commands/index.ts
- lib/core/client/client.ts
- lib/core/client/types.ts
[Y3-209](https://youcanshop.atlassian.net/browse/Y3-209)
[Y3-209]: https://youcanshop.atlassian.net/browse/Y3-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Y3-209 > Apps > CLI > As a developer I can create an app draft via CLI

- .eslintrc
- lib/cli/commands/apps/create.ts
- lib/cli/commands/apps/install.ts
- lib/cli/commands/auth/login.ts
- lib/cli/commands/auth/logout.ts
- lib/cli/commands/store/info.ts
- lib/cli/commands/store/switch.ts
- lib/cli/commands/theme/delete.ts
- lib/cli/commands/theme/dev.ts
- lib/cli/commands/theme/init.ts
- lib/cli/commands/theme/list.ts
- lib/cli/commands/theme/pack.ts
- lib/cli/commands/theme/pull.ts
- lib/cli/index.ts
- lib/core/client/client.ts
- lib/core/themes/preview.ts
- lib/utils/common.ts
- lib/utils/git/cloneRepository.ts
- lib/utils/helpers.ts
- lib/utils/http.ts
- lib/utils/network.ts
- lib/utils/system.ts
- lib/utils/system/deleteFile.ts
- lib/utils/system/openLink.ts
- lib/utils/system/saveFile.ts
- lib/utils/system/stdout.ts
- lib/utils/system/writeToFile.ts
- lib/utils/system/zipFolder.ts
- package.json
- pnpm-lock.yaml
Switched to youcan-ui's eslint config
> switch to @youcan/eslint-config

- packages/cli-kit/lib/node/env.ts
- packages/cli/bin/exec.js
- packages/cli/lib/cli/commands/auth/login.ts
- Fixes error when no active stores are found
- Added dev env config (use `YC_CLI_HOST_ENV=dev youcan auth login`)
- Default env to prod instead erroring
> dev env configuration and active store count check

- packages/app/lib/cli/commands/app/dev.ts
- packages/app/lib/cli/commands/app/generate/extension.ts
- packages/app/lib/cli/services/generate/generate.ts
- packages/app/lib/constants.ts
- packages/app/lib/util/theme-command.ts
> dark: constants fix

- packages/app/lib/cli/commands/app/dev.ts
- packages/app/lib/cli/commands/app/generate/extension.ts
- packages/app/lib/cli/services/dev/sync-extensions.ts
- packages/app/lib/cli/services/dev/workers/index.ts
- packages/app/lib/cli/services/dev/workers/theme-extension-worker.ts
- packages/app/lib/cli/services/generate/generate.ts
- packages/app/lib/constants.ts
- packages/app/lib/types.ts
- packages/app/lib/util/app-loader.ts
- packages/cli-kit/lib/node/filesystem.ts
- packages/cli-kit/lib/node/path.ts
- packages/cli-kit/lib/node/tasks.ts
- packages/cli-kit/package.json
- packages/create-app/lib/services/init.ts
- pnpm-lock.yaml
- Added a dev worker for theme extensions to handle realtime sync
> dark: init theme extension dev worker

- packages/cli-kit/lib/node/http.ts
- packages/theme/lib/cli/commands/theme/dev.ts
- packages/theme/lib/cli/services/dev/worker.ts
- packages/theme/lib/types.ts
- packages/theme/package.json
- pnpm-lock.yaml
> themes: dev worker preview socket

- packages/app/lib/cli/commands/app/dev.ts
- packages/app/lib/cli/commands/app/install.ts
- packages/app/lib/cli/services/dev/workers/theme-extension-worker.ts
- packages/cli-kit/lib/node/env.ts
- Changed main development domain from `youcanshop.dev` to `youcan.shop`.
- Updated draft app development urls.
> chore: update to live env urls

- packages/theme/lib/cli/services/dev/worker.ts
- Does the initial sync before starting the preview server to avoid the reload spam.
> fix(themes): sync before starting the preview server

- packages/theme/lib/cli/commands/theme/dev.ts
- packages/theme/lib/cli/services/dev/execute.ts
- packages/theme/lib/cli/services/dev/worker.ts
- packages/theme/lib/constants.ts
- Fixed an issue where the preview would start before the theme development worker.
> fix(themes): sync before booting the dev worker

- packages/create-app/bin/exec.js
- packages/create-app/lib/commands/init.ts
- packages/create-app/lib/prompts/init.ts
- pnpm-lock.yaml
```
pnpm dlx {path_to_cloned_repo}/packages/create-app/
```
> DARK : cli > handle ctr+c

- packages/cli-kit/lib/node/crypto.ts
- packages/cli-kit/lib/node/env.ts
- packages/cli-kit/lib/node/session.ts
- Switched authentication method to PKCE and changed the prod oauth client to keep backwards compat
> feat(cli-kit): use pkce for authentication

- packages/app/lib/cli/commands/app/dev.ts
- packages/app/lib/types.ts
- packages/app/lib/util/app-command.ts
[APPS-3](https://youcanshop.atlassian.net/browse/APPS-3)
[APPS-3]: https://youcanshop.atlassian.net/browse/APPS-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APPS-3 : Automatically configure the app's env when running dev - 2 

- packages/app/lib/cli/commands/app/dev.ts
- packages/app/lib/cli/services/dev/workers/tunnel-worker.ts
- packages/cli-kit/lib/node/system.ts
- packages/cli-kit/lib/services/cloudflared.ts
[APPS-13](https://youcanshop.atlassian.net/browse/APPS-13)
[APPS-13]: https://youcanshop.atlassian.net/browse/APPS-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APPS-13 : Rotate to the next port if the current chosen one is busy

- packages/cli-kit/lib/internal/node/ui.ts
> DARK > show cursor after loader ends

- packages/app/lib/cli/commands/app/dev.ts
- packages/app/lib/cli/services/dev/workers/tunnel-worker.ts
- packages/app/lib/util/app-command.ts
- packages/cli-kit/lib/node/cli.ts
- packages/cli-kit/lib/node/session.ts
- packages/theme/lib/cli/commands/theme/dev.ts
- packages/theme/lib/cli/services/dev/worker.ts
[APPS-23](https://youcanshop.atlassian.net/browse/APPS-23)
[APPS-23]: https://youcanshop.atlassian.net/browse/APPS-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APPS-23: Disallow auth for non dev stores

- packages/cli-kit/lib/scripts/install-cloudflared.ts
- packages/cli-kit/lib/services/cloudflared.ts
- packages/cli-kit/package.json
[CORE-412](https://youcanshop.atlassian.net/browse/CORE-412)
[CORE-412]: https://youcanshop.atlassian.net/browse/CORE-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-412 : Apps > Install the Cloudflared binary when installing the CLI packages

- packages/app/lib/cli/commands/app/dev.ts
- packages/cli-kit/lib/node/system.ts
- packages/cli-kit/package.json
- pnpm-lock.yaml
[CORE-430](https://youcanshop.atlassian.net/browse/CORE-430)
[CORE-430]: https://youcanshop.atlassian.net/browse/CORE-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CORE-430 : Fix `youcan app dev` command port issues

- packages/app/lib/cli/commands/app/dev.ts
- packages/cli-kit/lib/node/system.ts
- packages/cli/lib/index.ts
Fixes an issue where the apps web worker would not properly terminate its child processes.
> fix(apps): dev worker graceful shutdown
